### ISSUE TITLE
"Take the tour" button missing from "Tor" page

### ISSUE THREAD

**Issue by Darkwa** [plaperdr/fp-central#2]
"Take the tour" button is only visible on the "My fingerprint" page .
Since a part of the explanations is about the "TOR" page, it could be great to add a button to this page in order to get those informations easily.

**Comment by plaperdr** [comment]
This is indeed a great suggestion! I have added the button in both the 'Tor' and the 'Global stats' pages in commit 3bd10a2d67d4c4e1de221c6a7ebca0e856781214. I decided against adding one for the last two pages since the added information was not that useful. Thanks a lot for your help in making FP Central better!
